# Generated by Django 4.1 on 2022-08-22 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_word', models.CharField(max_length=30)),
                ('ukr_word', models.CharField(max_length=30)),
                ('correct_answers', models.SmallIntegerField(default=0, verbose_name='Кількість правильних відповідей')),
                ('last_answer', models.DateTimeField(auto_now=True, verbose_name='Час останньої відповіді')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='words.category')),
            ],
            options={
                'unique_together': {('eng_word', 'category')},
            },
        ),
    ]
